name: flutter_starter_todo_app
description: 'A simple starter todo app built using Flutter, BLoC and Isar'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

scripts:
  generate:
    icons: dart pub run flutter_launcher_icons
    files: dart pub run build_runner build --delete-conflicting-outputs
  build:
    android:
      apk: flutter build apk --flavor production -t lib/main.dart
      bundle: flutter build appbundle --flavor production -t lib/main.dart
    ios:
      ipa: flutter build ipa --flavor production -t lib/main.dart
      ios: flutter build ios --flavor production -t lib/main.dart

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  animated_theme_switcher: ^2.0.9
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0

dev_dependencies:
  analyzer: ^5.13.0
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mockito: ^5.4.3
  mocktail: ^1.0.1

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logo.jpg'
  min_sdk_android: 21
  # web:
  #   generate: true
  #   image_path: 'assets/images/logo.jpg'
  #   background_color: '#FFFFFF'
  #   theme_color: '#4E52D8'
  # windows:
  #   generate: true
  #   image_path: 'assets/images/logo.jpg'
  #   icon_size: 48
  # macos:
  #   generate: true
  #   image_path: 'assets/images/logo.jpg'

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf
