// Mocks generated by Mockito 5.4.3 from annotations
// in flutter_starter_todo_app/test/test/_mocks/data_sources/local_todo_service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_starter_todo_app/features/todo/data/data_sources/local/local_todo_service.dart'
    as _i2;
import 'package:flutter_starter_todo_app/features/todo/domain/entities/todo_entity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalTodoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalTodoService extends _i1.Mock implements _i2.LocalTodoService {
  @override
  _i3.Future<List<_i4.TodoEntity>> getTodos() => (super.noSuchMethod(
        Invocation.method(
          #getTodos,
          [],
        ),
        returnValue: _i3.Future<List<_i4.TodoEntity>>.value(<_i4.TodoEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.TodoEntity>>.value(<_i4.TodoEntity>[]),
      ) as _i3.Future<List<_i4.TodoEntity>>);

  @override
  _i3.Future<bool> addTodo(_i4.TodoEntity? todo) => (super.noSuchMethod(
        Invocation.method(
          #addTodo,
          [todo],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeTodo(int? id) => (super.noSuchMethod(
        Invocation.method(
          #removeTodo,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> toggleTodo(int? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleTodo,
          [id],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
